// Generated by tools/sync-game-config-from-spreadsheet.py.
// Edit game-config/game-config.xlsx, then run `npm run sync:game-config`.

export const cards = [
  {
    "name": "R1",
    "rarity": "R",
    "image": "/images/cards/player/R1/card.webp"
  },
  {
    "name": "R2",
    "rarity": "R",
    "image": "/images/cards/player/R2/card.webp"
  },
  {
    "name": "R3",
    "rarity": "R",
    "image": "/images/cards/player/R3/card.webp"
  },
  {
    "name": "R4",
    "rarity": "R",
    "image": "/images/cards/player/R4/card.webp"
  },
  {
    "name": "SR1",
    "rarity": "SR",
    "image": "/images/cards/player/SR1/card.webp"
  },
  {
    "name": "SR2",
    "rarity": "SR",
    "image": "/images/cards/player/SR2/card.webp"
  },
  {
    "name": "SR3",
    "rarity": "SR",
    "image": "/images/cards/player/SR3/card.webp"
  },
  {
    "name": "SR4",
    "rarity": "SR",
    "image": "/images/cards/player/SR4/card.webp"
  },
  {
    "name": "SSR1",
    "rarity": "SSR",
    "image": "/images/cards/player/SSR1/card.webp"
  },
  {
    "name": "SSR2",
    "rarity": "SSR",
    "image": "/images/cards/player/SSR2/card.webp"
  },
  {
    "name": "SSR3",
    "rarity": "SSR",
    "image": "/images/cards/player/SSR3/card.webp"
  },
  {
    "name": "SSR4",
    "rarity": "SSR",
    "image": "/images/cards/player/SSR4/card.webp"
  },
  {
    "name": "UR1",
    "rarity": "UR",
    "image": "/images/cards/player/UR1/card.webp"
  },
  {
    "name": "UR2",
    "rarity": "UR",
    "image": "/images/cards/player/UR2/card.webp"
  },
  {
    "name": "UR3",
    "rarity": "UR",
    "image": "/images/cards/player/UR3/card.webp"
  }
] as const;

export const rarityRates = {
  "R": 60.0,
  "SR": 25.0,
  "SSR": 10.0,
  "UR": 5.0
} as const;

export const playerCardProfiles = {
  "R": {
    "title": "Standard Fighter",
    "abilityName": "Steady Draw",
    "abilityText": "Acts as one battle life.",
    "lifeValue": 1,
    "cutInLevel": "normal"
  },
  "SR": {
    "title": "Skilled Fighter",
    "abilityName": "Blue Spark",
    "abilityText": "Acts as one battle life. Higher rarity presentation.",
    "lifeValue": 1,
    "cutInLevel": "rare"
  },
  "SSR": {
    "title": "Elite Fighter",
    "abilityName": "Golden Sign",
    "abilityText": "Acts as one battle life. Strong presentation priority.",
    "lifeValue": 1,
    "cutInLevel": "epic"
  },
  "UR": {
    "title": "Ultimate Fighter",
    "abilityName": "Rainbow Omen",
    "abilityText": "Acts as one battle life. Highest presentation priority.",
    "lifeValue": 1,
    "cutInLevel": "legend"
  }
} as const;

export const battleEnemies = {
  "1": {
    "id": 1,
    "name": "Enemy 1",
    "image": "/images/cards/enemy/enemy1/card.webp",
    "attackCounter": 5
  },
  "2": {
    "id": 2,
    "name": "Enemy 2",
    "image": "/images/cards/enemy/enemy2/card.webp",
    "attackCounter": 4
  },
  "3": {
    "id": 3,
    "name": "Enemy 3",
    "image": "/images/cards/enemy/enemy3/card.webp",
    "attackCounter": 7
  },
  "4": {
    "id": 4,
    "name": "Enemy 4",
    "image": "/images/cards/enemy/enemy4/card.webp",
    "attackCounter": 5
  },
  "5": {
    "id": 5,
    "name": "Enemy 5",
    "image": "/images/cards/enemy/enemy5/card.webp",
    "attackCounter": 8
  },
  "6": {
    "id": 6,
    "name": "Enemy 6",
    "image": "/images/cards/enemy/enemy6/card.webp",
    "attackCounter": 6
  },
  "7": {
    "id": 7,
    "name": "Enemy 7",
    "image": "/images/cards/enemy/enemy7/card.webp",
    "attackCounter": 4
  },
  "8": {
    "id": 8,
    "name": "Enemy 8",
    "image": "/images/cards/enemy/enemy8/card.webp",
    "attackCounter": 9
  },
  "9": {
    "id": 9,
    "name": "Enemy 9",
    "image": "/images/cards/enemy/enemy9/card.webp",
    "attackCounter": 9
  },
  "10": {
    "id": 10,
    "name": "Enemy 10",
    "image": "/images/cards/enemy/enemy10/card.webp",
    "attackCounter": 15
  },
  "11": {
    "id": 11,
    "name": "Enemy 11",
    "image": "/images/cards/enemy/enemy11/card.webp",
    "attackCounter": 5
  },
  "12": {
    "id": 12,
    "name": "Enemy 12",
    "image": "/images/cards/enemy/enemy12/card.webp",
    "attackCounter": 8
  },
  "13": {
    "id": 13,
    "name": "Enemy 13",
    "image": "/images/cards/enemy/enemy13/card.webp",
    "attackCounter": 11
  }
} as const;

export const enemySelectionGroups = [
  {
    "phase": "normal",
    "rounds": "2,3,4,6,7,8,9",
    "group": "common",
    "weight": 60.0,
    "enemyIds": [
      1,
      2,
      4,
      7,
      11
    ]
  },
  {
    "phase": "normal",
    "rounds": "2,3,4,6,7,8,9",
    "group": "rare",
    "weight": 27.0,
    "enemyIds": [
      3,
      5,
      6,
      8,
      9
    ]
  },
  {
    "phase": "normal",
    "rounds": "2,3,4,6,7,8,9",
    "group": "special",
    "weight": 3.0,
    "enemyIds": [
      10
    ]
  },
  {
    "phase": "chance",
    "rounds": "1,5,10",
    "group": "common",
    "weight": 35.0,
    "enemyIds": [
      1,
      2,
      4,
      7,
      11
    ]
  },
  {
    "phase": "chance",
    "rounds": "1,5,10",
    "group": "rare",
    "weight": 60.0,
    "enemyIds": [
      3,
      5,
      6,
      8,
      9
    ]
  },
  {
    "phase": "chance",
    "rounds": "1,5,10",
    "group": "special",
    "weight": 5.0,
    "enemyIds": [
      10
    ]
  },
  {
    "phase": "extra",
    "rounds": "11+",
    "group": "reset",
    "weight": 55.0,
    "enemyIds": [
      12
    ]
  },
  {
    "phase": "extra",
    "rounds": "11+",
    "group": "boss",
    "weight": 20.0,
    "enemyIds": [
      13
    ]
  },
  {
    "phase": "extra",
    "rounds": "11+",
    "group": "mixed",
    "weight": 25.0,
    "enemyIds": [
      1,
      3,
      10
    ]
  }
] as const;

export const battleResultOdds = [
  {
    "result": "Attack",
    "odds": 2.0
  },
  {
    "result": "Defense",
    "odds": 24.0
  },
  {
    "result": "Coin",
    "odds": 22.0
  },
  {
    "result": "Reply",
    "odds": 8.0
  },
  {
    "result": "Bar",
    "odds": 1000.0
  },
  {
    "result": "SingleChance",
    "odds": 37.0
  },
  {
    "result": "DoubleChance",
    "odds": 114.0
  },
  {
    "result": "TripleChance",
    "odds": 800.0
  }
] as const;

export const visualPatternsByResult = {
  "Attack": [
    {
      "cards": [
        "Coin",
        "Attack",
        "Empty"
      ],
      "weight": 15.0
    },
    {
      "cards": [
        "Defense",
        "Attack",
        "Empty"
      ],
      "weight": 10.0
    },
    {
      "cards": [
        "Reply",
        "Attack",
        "Empty"
      ],
      "weight": 10.0
    },
    {
      "cards": [
        "Attack",
        "Reply",
        "Empty"
      ],
      "weight": 10.0
    },
    {
      "cards": [
        "Attack",
        "Empty",
        "Empty"
      ],
      "weight": 10.0
    },
    {
      "cards": [
        "Bar",
        "Empty",
        "Attack"
      ],
      "weight": 10.0
    },
    {
      "cards": [
        "Coin",
        "Coin",
        "Attack"
      ],
      "weight": 10.0
    },
    {
      "cards": [
        "Defense",
        "Defense",
        "Attack"
      ],
      "weight": 10.0
    },
    {
      "cards": [
        "Attack",
        "Attack",
        "Attack"
      ],
      "weight": 3.0
    },
    {
      "cards": [
        "Coin",
        "Attack",
        "Attack"
      ],
      "weight": 6.0
    },
    {
      "cards": [
        "Attack",
        "Reply",
        "Attack"
      ],
      "weight": 6.0
    }
  ],
  "Defense": [
    {
      "cards": [
        "Defense",
        "Defense",
        "Defense"
      ],
      "weight": 100.0
    }
  ],
  "SingleChance": [
    {
      "cards": [
        "Chance",
        "Reply",
        "Bar"
      ],
      "weight": 30.0
    },
    {
      "cards": [
        "Bar",
        "Chance",
        "Empty"
      ],
      "weight": 20.0
    },
    {
      "cards": [
        "Coin",
        "Chance",
        "Empty"
      ],
      "weight": 20.0
    },
    {
      "cards": [
        "Bar",
        "Bar",
        "Chance"
      ],
      "weight": 10.0
    },
    {
      "cards": [
        "Reply",
        "Empty",
        "Chance"
      ],
      "weight": 20.0
    }
  ],
  "DoubleChance": [
    {
      "cards": [
        "Chance",
        "Chance",
        "Bar"
      ],
      "weight": 40.0
    },
    {
      "cards": [
        "Bar",
        "Chance",
        "Chance"
      ],
      "weight": 30.0
    },
    {
      "cards": [
        "Chance",
        "Reply",
        "Chance"
      ],
      "weight": 30.0
    }
  ],
  "TripleChance": [
    {
      "cards": [
        "Chance",
        "Chance",
        "Chance"
      ],
      "weight": 100.0
    }
  ],
  "Coin": [
    {
      "cards": [
        "Coin",
        "Coin",
        "Coin"
      ],
      "weight": 100.0
    }
  ],
  "Reply": [
    {
      "cards": [
        "Reply",
        "Reply",
        "Reply"
      ],
      "weight": 100.0
    }
  ],
  "Bar": [
    {
      "cards": [
        "Bar",
        "Bar",
        "Bar"
      ],
      "weight": 100.0
    }
  ],
  "Empty": [
    {
      "cards": [
        "Coin",
        "Coin",
        "Empty"
      ],
      "weight": 25.0
    },
    {
      "cards": [
        "Defense",
        "Defense",
        "Empty"
      ],
      "weight": 25.0
    },
    {
      "cards": [
        "Reply",
        "Reply",
        "Bar"
      ],
      "weight": 25.0
    },
    {
      "cards": [
        "Bar",
        "Bar",
        "Empty"
      ],
      "weight": 10.0
    },
    {
      "cards": [
        "Reply",
        "Empty",
        "Empty"
      ],
      "weight": 15.0
    }
  ]
} as const;

export const BONUS_POINTS = {
  "Attack": 10,
  "Defense": 20,
  "Reply": 20,
  "Chance": 30,
  "Empty": 5,
  "Bar": 50
} as const;

export const bonusRewards = {
  "Attack": {
    "points": 20,
    "video": "/videos/bonus-reveals/20.mp4"
  },
  "Defense": {
    "points": 30,
    "video": "/videos/bonus-reveals/30.mp4"
  },
  "Reply": {
    "points": 50,
    "video": "/videos/bonus-reveals/50.mp4"
  },
  "SingleChance": {
    "points": 100,
    "video": "/videos/bonus-reveals/100.mp4"
  },
  "DoubleChance": {
    "points": 200,
    "video": "/videos/bonus-reveals/200.mp4"
  },
  "TripleChance": {
    "points": 300,
    "video": "/videos/bonus-reveals/300.mp4"
  },
  "Fallback": {
    "points": 20,
    "video": "/videos/bonus-reveals/20.mp4"
  },
  "BarReset": {
    "points": 0,
    "video": "/videos/bonus-reveals/reset.mp4"
  }
} as const;

export const APP_NUMBERS = {
  "GAME_WIDTH": 1920.0,
  "GAME_HEIGHT": 1080.0,
  "STAGE_WIDTH": 1200.0,
  "STAGE_HEIGHT": 500.0,
  "TABLE_X": 600.0,
  "TABLE_Y": 250.0,
  "TABLE_SCALE": 0.4,
  "HOLDER_X": 160.0,
  "HOLDER_Y": 250.0,
  "HOLDER_SCALE": 0.6,
  "DRAW_BUTTON_X": 170.0,
  "DRAW_BUTTON_Y": 250.0,
  "DRAW_BUTTON_SCALE": 0.6,
  "CARD_START_X": 132.0,
  "CARD_START_Y": 250.0,
  "CARD_END_X": 313.0,
  "CARD_END_Y": 250.0,
  "CARD_SCALE": 0.2,
  "RELEASE_DISTANCE": 100.0,
  "SLOT1_X": 420.0,
  "SLOT1_Y": 250.0,
  "SLOT2_X": 600.0,
  "SLOT2_Y": 250.0,
  "SLOT3_X": 780.0,
  "SLOT3_Y": 250.0,
  "CARD_PLACE_DURATION_1": 150.0,
  "CARD_PLACE_DURATION_2": 250.0,
  "CARD_PLACE_DURATION_3": 350.0,
  "CHANCE_RATE_PER_CARD": 30.0
} as const;

export const adminSettings = [
  {
    "key": "welcome_gift_points",
    "defaultValue": 0.0,
    "description": "Welcome gift"
  },
  {
    "key": "single_pull_cost",
    "defaultValue": 0.0,
    "description": "Single pull cost"
  },
  {
    "key": "ten_pull_cost",
    "defaultValue": 0.0,
    "description": "Ten pull cost"
  },
  {
    "key": "return_R",
    "defaultValue": 0.0,
    "description": "R return points"
  },
  {
    "key": "return_SR",
    "defaultValue": 0.0,
    "description": "SR return points"
  },
  {
    "key": "return_SSR",
    "defaultValue": 0.0,
    "description": "SSR return points"
  },
  {
    "key": "return_UR",
    "defaultValue": 0.0,
    "description": "UR return points"
  },
  {
    "key": "starting_points",
    "defaultValue": 0.0,
    "description": "Starting points"
  },
  {
    "key": "member_daily_points",
    "defaultValue": 0.0,
    "description": "Member daily points"
  },
  {
    "key": "guest_daily_points",
    "defaultValue": 0.0,
    "description": "Guest daily points"
  },
  {
    "key": "battle_cost",
    "defaultValue": 0.0,
    "description": "Battle cost"
  },
  {
    "key": "reveal_ur_standard",
    "defaultValue": 20.0,
    "description": "UR reveal standard weight"
  },
  {
    "key": "reveal_ur_standard2",
    "defaultValue": 15.0,
    "description": "UR reveal standard2 weight"
  },
  {
    "key": "reveal_ur_ssr",
    "defaultValue": 15.0,
    "description": "UR reveal SSR weight"
  },
  {
    "key": "reveal_ur_ur1",
    "defaultValue": 37.0,
    "description": "UR reveal UR1 weight"
  },
  {
    "key": "reveal_ur_ur2",
    "defaultValue": 13.0,
    "description": "UR reveal UR2 weight"
  },
  {
    "key": "reveal_ssr_standard",
    "defaultValue": 35.0,
    "description": "SSR reveal standard weight"
  },
  {
    "key": "reveal_ssr_standard2",
    "defaultValue": 25.0,
    "description": "SSR reveal standard2 weight"
  },
  {
    "key": "reveal_ssr_ssr",
    "defaultValue": 40.0,
    "description": "SSR reveal SSR weight"
  },
  {
    "key": "reveal_sr3_standard",
    "defaultValue": 40.0,
    "description": "3+ SR reveal standard weight"
  },
  {
    "key": "reveal_sr3_standard2",
    "defaultValue": 60.0,
    "description": "3+ SR reveal standard2 weight"
  },
  {
    "key": "reveal_default_standard",
    "defaultValue": 80.0,
    "description": "Default reveal standard weight"
  },
  {
    "key": "reveal_default_standard2",
    "defaultValue": 20.0,
    "description": "Default reveal standard2 weight"
  },
  {
    "key": "reveal_freeze_chance",
    "defaultValue": 25.0,
    "description": "Freeze chance percent"
  }
] as const;

export const CHANCE_RATE_PER_CARD = APP_NUMBERS.CHANCE_RATE_PER_CARD;

export const GAME = {
  WIDTH: APP_NUMBERS.GAME_WIDTH,
  HEIGHT: APP_NUMBERS.GAME_HEIGHT,
} as const;

export const STAGE = {
  WIDTH: APP_NUMBERS.STAGE_WIDTH,
  HEIGHT: APP_NUMBERS.STAGE_HEIGHT,
} as const;

export const UI = {
  TABLE_X: APP_NUMBERS.TABLE_X,
  TABLE_Y: APP_NUMBERS.TABLE_Y,
  TABLE_SCALE: APP_NUMBERS.TABLE_SCALE,
  HOLDER_X: APP_NUMBERS.HOLDER_X,
  HOLDER_Y: APP_NUMBERS.HOLDER_Y,
  HOLDER_SCALE: APP_NUMBERS.HOLDER_SCALE,
  DRAW_BUTTON_X: APP_NUMBERS.DRAW_BUTTON_X,
  DRAW_BUTTON_Y: APP_NUMBERS.DRAW_BUTTON_Y,
  DRAW_BUTTON_SCALE: APP_NUMBERS.DRAW_BUTTON_SCALE,
  CARD_START_X: APP_NUMBERS.CARD_START_X,
  CARD_START_Y: APP_NUMBERS.CARD_START_Y,
  CARD_END_X: APP_NUMBERS.CARD_END_X,
  CARD_END_Y: APP_NUMBERS.CARD_END_Y,
  CARD_SCALE: APP_NUMBERS.CARD_SCALE,
  CARD_ROTATION: Math.PI / 2,
  RELEASE_DISTANCE: APP_NUMBERS.RELEASE_DISTANCE,
  SLOT1_X: APP_NUMBERS.SLOT1_X,
  SLOT1_Y: APP_NUMBERS.SLOT1_Y,
  SLOT2_X: APP_NUMBERS.SLOT2_X,
  SLOT2_Y: APP_NUMBERS.SLOT2_Y,
  SLOT3_X: APP_NUMBERS.SLOT3_X,
  SLOT3_Y: APP_NUMBERS.SLOT3_Y,
  CARD_PLACE_DURATION_1: APP_NUMBERS.CARD_PLACE_DURATION_1,
  CARD_PLACE_DURATION_2: APP_NUMBERS.CARD_PLACE_DURATION_2,
  CARD_PLACE_DURATION_3: APP_NUMBERS.CARD_PLACE_DURATION_3,
} as const;
